### ISSUE TITLE
why does SF have so few commits?

### ISSUE THREAD

**Issue by tofr** [sfomina/StringCheese#2]
?
?
?

**Comment by sfomina** [comment]
I think I have 8 commits. I'll try to commit more, but I tend to commit large loads of changes at once. The devlog is updated with all my work.
Update: when I look at the day by day, it says I have 8 commits, but when I look at the graphs it says I only have 2? I have 2 emails, but only one github account, so I'm not sure how that happened.  
Update: I have a new laptop and I never set the email configuration to my stuy.edu email, so most commits were made under a different email.

**Comment by tofr** [comment]
Good.

Topher Brown Mykolyk
CS - Stuyvesant HS
+
